# Generated by Django 3.2.3 on 2021-05-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra_produto',
            name='valor_medio',
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_medio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Preço Médio'),
        ),
    ]
